name: Release Processor

on:
  release:
    types: [published]

jobs:
  release-info:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show Release Information
        run: |
          echo "Release Name: ${{ github.event.release.name }}"
          echo "Tag: ${{ github.event.release.tag_name }}"

      - name: Download Release Assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir assets

          gh release download ${{ github.event.release.tag_name }} \
            --repo ${{ github.repository }} \
            --dir assets

          echo "Downloaded files:"
          ls -la assets
